### ISSUE TITLE
Update sources added by craft-archives

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-archives#151]
### What needs to get done

#150 sets architectures for sources in `/etc/apt/sources.list.d/ubuntu.sources`.

It doesn't set architectures for other repositories added by craft-archives in `/etc/apt/sources.list.d/craft-*.sources`.

For example, consider the following project file snippet:
```yaml
platforms:
  riscv64:
    build-on: [amd64]
    build-for: [riscv64]

package-repositories:
  - type: apt
    # architectures: [amd64] - won't this solve the problem?
    formats: [deb]
    components: [main]
    suites: [noble]
    key-id: F23C5A6CF475977595C89F51BA6932366A755776
    url: https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu

  - type: apt
    architectures: [riscv64]
    formats: [deb, deb-src]
    components: [main]
    suites: [noble, noble-updates, noble-backports]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports
```

### Why it needs to get done

To support cross-compiling in *craft applications.
